# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4aa06368556e0b143489c1f08cffcf0619bd6aae0f06dba824056fbc83f0c9739243910ced9d9ef26841c09d2158d4406602c9df3ee9a3dcecc1745c6f69d830

test:
  secret_key_base: 052e7aac02932ebb858d0f5d5e7826ebd49015ed2f8f620778a67f92ea4f9bb41a8488f554207a2c11d8b880ba1ddcc6e6b297c4bdc862c2d287cdefa0cfd78e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
